package auth

import (
	"testing"

	"github.com/google/uuid"
	"github.com/stretchr/testify/require"
)

// TestTokenManagerGenerateAndVerify ensures that tokens generated by the
// TokenManager can be verified and yield the correct subject. It uses
// GenerateKeyPair to create an in-memory RSA key pair for signing.
func TestTokenManagerGenerateAndVerify(t *testing.T) {
	priv, pub, err := GenerateKeyPair()
	require.NoError(t, err)
	tm := &TokenManager{privateKey: priv, publicKey: pub}
	uid := uuid.New().String()
	access, refresh, err := tm.Generate(uid)
	require.NoError(t, err)
	require.NotEmpty(t, access)
	require.NotEmpty(t, refresh)
	sub, err := tm.Verify(access)
	require.NoError(t, err)
	require.Equal(t, uid, sub)
}

// TestTokenManagerVerifyInvalid ensures that invalid or tampered tokens
// produce an error on verification.
func TestTokenManagerVerifyInvalid(t *testing.T) {
	priv, pub, err := GenerateKeyPair()
	require.NoError(t, err)
	tm := &TokenManager{privateKey: priv, publicKey: pub}
	_, refresh, err := tm.Generate("foo")
	require.NoError(t, err)
	// Tamper with the token by appending junk
	_, err = tm.Verify(refresh + "junk")
	require.Error(t, err)
}
